db :
  dsn : root:root@tcp(127.0.0.1:3306)/community?charset=utf8mb4&parseTime=True&loc=Local
  SetMaxIdleConns: 10
  SetMaxOpenConns: 10

  redis : localhost:6379

server :
  port : 9091

mode :
  develop : false

token :
  SignKey : "CommunityKey"

custom:
  prefix : Community_test_